BEGIN;

DROP TABLE IF EXISTS objectType;
DROP TABLE IF EXISTS warrant;
DROP TABLE IF EXISTS context;
DROP TABLE IF EXISTS object;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS tenant;
DROP TABLE IF EXISTS user;

COMMIT;
