BEGIN;

CREATE TABLE IF NOT EXISTS wookie (
  id bigint NOT NULL AUTO_INCREMENT,
  ver bigint NOT NULL,
  createdAt timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

COMMIT;
