// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.2
// source: GroupService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GroupService_KickoutAllGroupForUser_FullMethodName     = "/GroupService/kickoutAllGroupForUser"
	GroupService_KickoutAllGroupForUserBase_FullMethodName = "/GroupService/kickoutAllGroupForUserBase"
	GroupService_GetAll_FullMethodName                     = "/GroupService/getAll"
	GroupService_Create_FullMethodName                     = "/GroupService/create"
	GroupService_Join_FullMethodName                       = "/GroupService/join"
	GroupService_Leave_FullMethodName                      = "/GroupService/leave"
	GroupService_Edit_FullMethodName                       = "/GroupService/edit"
	GroupService_Announcement_FullMethodName               = "/GroupService/announcement"
	GroupService_GetGroupMembers_FullMethodName            = "/GroupService/getGroupMembers"
	GroupService_GetMyGroups_FullMethodName                = "/GroupService/getMyGroups"
	GroupService_ChangeRole_FullMethodName                 = "/GroupService/changeRole"
	GroupService_BulkJoin_FullMethodName                   = "/GroupService/bulkJoin"
	GroupService_UploadAvatar_FullMethodName               = "/GroupService/uploadAvatar"
	GroupService_DismissGroup_FullMethodName               = "/GroupService/dismissGroup"
	GroupService_ChangeGroupExtForUser_FullMethodName      = "/GroupService/changeGroupExtForUser"
	GroupService_GetMember_FullMethodName                  = "/GroupService/getMember"
	GroupService_GetGroup_FullMethodName                   = "/GroupService/getGroup"
	GroupService_GetGroupMembersForProto_FullMethodName    = "/GroupService/getGroupMembersForProto"
	GroupService_UpdateGroupActiveTime_FullMethodName      = "/GroupService/updateGroupActiveTime"
	GroupService_GetMemberGroups_FullMethodName            = "/GroupService/getMemberGroups"
	GroupService_IsAllowPrivateChat_FullMethodName         = "/GroupService/isAllowPrivateChat"
	GroupService_GetPrivateChatGroups_FullMethodName       = "/GroupService/getPrivateChatGroups"
	GroupService_SubscribeGroup_FullMethodName             = "/GroupService/subscribeGroup"
)

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupServiceClient interface {
	KickoutAllGroupForUser(ctx context.Context, in *UidsRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	KickoutAllGroupForUserBase(ctx context.Context, in *BaseAnyRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetAll(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*GroupsResponse, error)
	Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	Join(ctx context.Context, in *GroupsCreateRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	Leave(ctx context.Context, in *GroupsCreateRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	Edit(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	Announcement(ctx context.Context, in *GroupsAnnouncementRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetGroupMembers(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetMyGroups(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	ChangeRole(ctx context.Context, in *GroupMembersResponse, opts ...grpc.CallOption) (*BaseResponse, error)
	BulkJoin(ctx context.Context, in *GroupJoinRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UploadAvatar(ctx context.Context, in *GroupAvatarRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	DismissGroup(ctx context.Context, in *GroupDismissRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	ChangeGroupExtForUser(ctx context.Context, in *BaseAnyRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetMember(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetGroupMembersForProto(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UpdateGroupActiveTime(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetMemberGroups(ctx context.Context, in *MemberGroupRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	IsAllowPrivateChat(ctx context.Context, in *PrivateChatRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetPrivateChatGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResponse, error)
	SubscribeGroup(ctx context.Context, in *GroupSubscribeRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) KickoutAllGroupForUser(ctx context.Context, in *UidsRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_KickoutAllGroupForUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) KickoutAllGroupForUserBase(ctx context.Context, in *BaseAnyRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_KickoutAllGroupForUserBase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetAll(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*GroupsResponse, error) {
	out := new(GroupsResponse)
	err := c.cc.Invoke(ctx, GroupService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Join(ctx context.Context, in *GroupsCreateRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_Join_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Leave(ctx context.Context, in *GroupsCreateRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_Leave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Edit(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_Edit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Announcement(ctx context.Context, in *GroupsAnnouncementRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_Announcement_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroupMembers(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetGroupMembers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetMyGroups(ctx context.Context, in *GroupsRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetMyGroups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ChangeRole(ctx context.Context, in *GroupMembersResponse, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_ChangeRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) BulkJoin(ctx context.Context, in *GroupJoinRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_BulkJoin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UploadAvatar(ctx context.Context, in *GroupAvatarRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_UploadAvatar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DismissGroup(ctx context.Context, in *GroupDismissRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_DismissGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ChangeGroupExtForUser(ctx context.Context, in *BaseAnyRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_ChangeGroupExtForUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetMember(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroupMembersForProto(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetGroupMembersForProto_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateGroupActiveTime(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_UpdateGroupActiveTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetMemberGroups(ctx context.Context, in *MemberGroupRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetMemberGroups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) IsAllowPrivateChat(ctx context.Context, in *PrivateChatRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_IsAllowPrivateChat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetPrivateChatGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_GetPrivateChatGroups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) SubscribeGroup(ctx context.Context, in *GroupSubscribeRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, GroupService_SubscribeGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
// All implementations must embed UnimplementedGroupServiceServer
// for forward compatibility
type GroupServiceServer interface {
	KickoutAllGroupForUser(context.Context, *UidsRequest) (*BaseResponse, error)
	KickoutAllGroupForUserBase(context.Context, *BaseAnyRequest) (*BaseResponse, error)
	GetAll(context.Context, *GroupsRequest) (*GroupsResponse, error)
	Create(context.Context, *CreateGroupRequest) (*BaseResponse, error)
	Join(context.Context, *GroupsCreateRequest) (*BaseResponse, error)
	Leave(context.Context, *GroupsCreateRequest) (*BaseResponse, error)
	Edit(context.Context, *GroupsRequest) (*BaseResponse, error)
	Announcement(context.Context, *GroupsAnnouncementRequest) (*BaseResponse, error)
	GetGroupMembers(context.Context, *GroupsRequest) (*BaseResponse, error)
	GetMyGroups(context.Context, *GroupsRequest) (*BaseResponse, error)
	ChangeRole(context.Context, *GroupMembersResponse) (*BaseResponse, error)
	BulkJoin(context.Context, *GroupJoinRequest) (*BaseResponse, error)
	UploadAvatar(context.Context, *GroupAvatarRequest) (*BaseResponse, error)
	DismissGroup(context.Context, *GroupDismissRequest) (*BaseResponse, error)
	ChangeGroupExtForUser(context.Context, *BaseAnyRequest) (*BaseResponse, error)
	GetMember(context.Context, *GroupMemberRequest) (*BaseResponse, error)
	GetGroup(context.Context, *GroupRequest) (*BaseResponse, error)
	GetGroupMembersForProto(context.Context, *GroupRequest) (*BaseResponse, error)
	UpdateGroupActiveTime(context.Context, *GroupMemberRequest) (*BaseResponse, error)
	GetMemberGroups(context.Context, *MemberGroupRequest) (*BaseResponse, error)
	IsAllowPrivateChat(context.Context, *PrivateChatRequest) (*BaseResponse, error)
	GetPrivateChatGroups(context.Context, *Empty) (*BaseResponse, error)
	SubscribeGroup(context.Context, *GroupSubscribeRequest) (*BaseResponse, error)
	mustEmbedUnimplementedGroupServiceServer()
}

// UnimplementedGroupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGroupServiceServer struct {
}

func (UnimplementedGroupServiceServer) KickoutAllGroupForUser(context.Context, *UidsRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickoutAllGroupForUser not implemented")
}
func (UnimplementedGroupServiceServer) KickoutAllGroupForUserBase(context.Context, *BaseAnyRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickoutAllGroupForUserBase not implemented")
}
func (UnimplementedGroupServiceServer) GetAll(context.Context, *GroupsRequest) (*GroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedGroupServiceServer) Create(context.Context, *CreateGroupRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGroupServiceServer) Join(context.Context, *GroupsCreateRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedGroupServiceServer) Leave(context.Context, *GroupsCreateRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedGroupServiceServer) Edit(context.Context, *GroupsRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedGroupServiceServer) Announcement(context.Context, *GroupsAnnouncementRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Announcement not implemented")
}
func (UnimplementedGroupServiceServer) GetGroupMembers(context.Context, *GroupsRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedGroupServiceServer) GetMyGroups(context.Context, *GroupsRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyGroups not implemented")
}
func (UnimplementedGroupServiceServer) ChangeRole(context.Context, *GroupMembersResponse) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeRole not implemented")
}
func (UnimplementedGroupServiceServer) BulkJoin(context.Context, *GroupJoinRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkJoin not implemented")
}
func (UnimplementedGroupServiceServer) UploadAvatar(context.Context, *GroupAvatarRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedGroupServiceServer) DismissGroup(context.Context, *GroupDismissRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DismissGroup not implemented")
}
func (UnimplementedGroupServiceServer) ChangeGroupExtForUser(context.Context, *BaseAnyRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeGroupExtForUser not implemented")
}
func (UnimplementedGroupServiceServer) GetMember(context.Context, *GroupMemberRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedGroupServiceServer) GetGroup(context.Context, *GroupRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedGroupServiceServer) GetGroupMembersForProto(context.Context, *GroupRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMembersForProto not implemented")
}
func (UnimplementedGroupServiceServer) UpdateGroupActiveTime(context.Context, *GroupMemberRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupActiveTime not implemented")
}
func (UnimplementedGroupServiceServer) GetMemberGroups(context.Context, *MemberGroupRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberGroups not implemented")
}
func (UnimplementedGroupServiceServer) IsAllowPrivateChat(context.Context, *PrivateChatRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAllowPrivateChat not implemented")
}
func (UnimplementedGroupServiceServer) GetPrivateChatGroups(context.Context, *Empty) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateChatGroups not implemented")
}
func (UnimplementedGroupServiceServer) SubscribeGroup(context.Context, *GroupSubscribeRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeGroup not implemented")
}
func (UnimplementedGroupServiceServer) mustEmbedUnimplementedGroupServiceServer() {}

// UnsafeGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServiceServer will
// result in compilation errors.
type UnsafeGroupServiceServer interface {
	mustEmbedUnimplementedGroupServiceServer()
}

func RegisterGroupServiceServer(s grpc.ServiceRegistrar, srv GroupServiceServer) {
	s.RegisterService(&GroupService_ServiceDesc, srv)
}

func _GroupService_KickoutAllGroupForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).KickoutAllGroupForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_KickoutAllGroupForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).KickoutAllGroupForUser(ctx, req.(*UidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_KickoutAllGroupForUserBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseAnyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).KickoutAllGroupForUserBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_KickoutAllGroupForUserBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).KickoutAllGroupForUserBase(ctx, req.(*BaseAnyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetAll(ctx, req.(*GroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Create(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Join(ctx, req.(*GroupsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Leave(ctx, req.(*GroupsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Edit(ctx, req.(*GroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Announcement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Announcement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Announcement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Announcement(ctx, req.(*GroupsAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroupMembers(ctx, req.(*GroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetMyGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetMyGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetMyGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetMyGroups(ctx, req.(*GroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ChangeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMembersResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ChangeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ChangeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ChangeRole(ctx, req.(*GroupMembersResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_BulkJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).BulkJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_BulkJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).BulkJoin(ctx, req.(*GroupJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UploadAvatar(ctx, req.(*GroupAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DismissGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupDismissRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DismissGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_DismissGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DismissGroup(ctx, req.(*GroupDismissRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ChangeGroupExtForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseAnyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ChangeGroupExtForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ChangeGroupExtForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ChangeGroupExtForUser(ctx, req.(*BaseAnyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetMember(ctx, req.(*GroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroup(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroupMembersForProto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroupMembersForProto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetGroupMembersForProto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroupMembersForProto(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateGroupActiveTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateGroupActiveTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateGroupActiveTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateGroupActiveTime(ctx, req.(*GroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetMemberGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetMemberGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetMemberGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetMemberGroups(ctx, req.(*MemberGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_IsAllowPrivateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).IsAllowPrivateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_IsAllowPrivateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).IsAllowPrivateChat(ctx, req.(*PrivateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetPrivateChatGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetPrivateChatGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetPrivateChatGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetPrivateChatGroups(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_SubscribeGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).SubscribeGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_SubscribeGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).SubscribeGroup(ctx, req.(*GroupSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupService_ServiceDesc is the grpc.ServiceDesc for GroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "kickoutAllGroupForUser",
			Handler:    _GroupService_KickoutAllGroupForUser_Handler,
		},
		{
			MethodName: "kickoutAllGroupForUserBase",
			Handler:    _GroupService_KickoutAllGroupForUserBase_Handler,
		},
		{
			MethodName: "getAll",
			Handler:    _GroupService_GetAll_Handler,
		},
		{
			MethodName: "create",
			Handler:    _GroupService_Create_Handler,
		},
		{
			MethodName: "join",
			Handler:    _GroupService_Join_Handler,
		},
		{
			MethodName: "leave",
			Handler:    _GroupService_Leave_Handler,
		},
		{
			MethodName: "edit",
			Handler:    _GroupService_Edit_Handler,
		},
		{
			MethodName: "announcement",
			Handler:    _GroupService_Announcement_Handler,
		},
		{
			MethodName: "getGroupMembers",
			Handler:    _GroupService_GetGroupMembers_Handler,
		},
		{
			MethodName: "getMyGroups",
			Handler:    _GroupService_GetMyGroups_Handler,
		},
		{
			MethodName: "changeRole",
			Handler:    _GroupService_ChangeRole_Handler,
		},
		{
			MethodName: "bulkJoin",
			Handler:    _GroupService_BulkJoin_Handler,
		},
		{
			MethodName: "uploadAvatar",
			Handler:    _GroupService_UploadAvatar_Handler,
		},
		{
			MethodName: "dismissGroup",
			Handler:    _GroupService_DismissGroup_Handler,
		},
		{
			MethodName: "changeGroupExtForUser",
			Handler:    _GroupService_ChangeGroupExtForUser_Handler,
		},
		{
			MethodName: "getMember",
			Handler:    _GroupService_GetMember_Handler,
		},
		{
			MethodName: "getGroup",
			Handler:    _GroupService_GetGroup_Handler,
		},
		{
			MethodName: "getGroupMembersForProto",
			Handler:    _GroupService_GetGroupMembersForProto_Handler,
		},
		{
			MethodName: "updateGroupActiveTime",
			Handler:    _GroupService_UpdateGroupActiveTime_Handler,
		},
		{
			MethodName: "getMemberGroups",
			Handler:    _GroupService_GetMemberGroups_Handler,
		},
		{
			MethodName: "isAllowPrivateChat",
			Handler:    _GroupService_IsAllowPrivateChat_Handler,
		},
		{
			MethodName: "getPrivateChatGroups",
			Handler:    _GroupService_GetPrivateChatGroups_Handler,
		},
		{
			MethodName: "subscribeGroup",
			Handler:    _GroupService_SubscribeGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GroupService.proto",
}
