// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.2
// source: InternalOrgService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InternalOrgService_QueryOrg_FullMethodName      = "/InternalOrgService/QueryOrg"
	InternalOrgService_CreateOrg_FullMethodName     = "/InternalOrgService/CreateOrg"
	InternalOrgService_UpdateOrg_FullMethodName     = "/InternalOrgService/UpdateOrg"
	InternalOrgService_QueryUserOrg_FullMethodName  = "/InternalOrgService/QueryUserOrg"
	InternalOrgService_SetUserOrg_FullMethodName    = "/InternalOrgService/SetUserOrg"
	InternalOrgService_RemoveUserOrg_FullMethodName = "/InternalOrgService/RemoveUserOrg"
	InternalOrgService_QueryOrgUsers_FullMethodName = "/InternalOrgService/QueryOrgUsers"
	InternalOrgService_QueryOrgAdmin_FullMethodName = "/InternalOrgService/QueryOrgAdmin"
	InternalOrgService_SetOrgAdmin_FullMethodName   = "/InternalOrgService/SetOrgAdmin"
	InternalOrgService_QueryUsersOrg_FullMethodName = "/InternalOrgService/QueryUsersOrg"
)

// InternalOrgServiceClient is the client API for InternalOrgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalOrgServiceClient interface {
	QueryOrg(ctx context.Context, in *QueryOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	CreateOrg(ctx context.Context, in *CreateOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UpdateOrg(ctx context.Context, in *UpdateOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	QueryUserOrg(ctx context.Context, in *QueryUserOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	SetUserOrg(ctx context.Context, in *SetUserOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	RemoveUserOrg(ctx context.Context, in *RemoveUserOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	QueryOrgUsers(ctx context.Context, in *QueryOrgUsersRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	QueryOrgAdmin(ctx context.Context, in *QueryOrgUsersRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	SetOrgAdmin(ctx context.Context, in *SetOrgAdminRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	QueryUsersOrg(ctx context.Context, in *QueryUsersOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type internalOrgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalOrgServiceClient(cc grpc.ClientConnInterface) InternalOrgServiceClient {
	return &internalOrgServiceClient{cc}
}

func (c *internalOrgServiceClient) QueryOrg(ctx context.Context, in *QueryOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_QueryOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) CreateOrg(ctx context.Context, in *CreateOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_CreateOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) UpdateOrg(ctx context.Context, in *UpdateOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_UpdateOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) QueryUserOrg(ctx context.Context, in *QueryUserOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_QueryUserOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) SetUserOrg(ctx context.Context, in *SetUserOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_SetUserOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) RemoveUserOrg(ctx context.Context, in *RemoveUserOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_RemoveUserOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) QueryOrgUsers(ctx context.Context, in *QueryOrgUsersRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_QueryOrgUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) QueryOrgAdmin(ctx context.Context, in *QueryOrgUsersRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_QueryOrgAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) SetOrgAdmin(ctx context.Context, in *SetOrgAdminRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_SetOrgAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalOrgServiceClient) QueryUsersOrg(ctx context.Context, in *QueryUsersOrgRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, InternalOrgService_QueryUsersOrg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalOrgServiceServer is the server API for InternalOrgService service.
// All implementations must embed UnimplementedInternalOrgServiceServer
// for forward compatibility
type InternalOrgServiceServer interface {
	QueryOrg(context.Context, *QueryOrgRequest) (*BaseResponse, error)
	CreateOrg(context.Context, *CreateOrgRequest) (*BaseResponse, error)
	UpdateOrg(context.Context, *UpdateOrgRequest) (*BaseResponse, error)
	QueryUserOrg(context.Context, *QueryUserOrgRequest) (*BaseResponse, error)
	SetUserOrg(context.Context, *SetUserOrgRequest) (*BaseResponse, error)
	RemoveUserOrg(context.Context, *RemoveUserOrgRequest) (*BaseResponse, error)
	QueryOrgUsers(context.Context, *QueryOrgUsersRequest) (*BaseResponse, error)
	QueryOrgAdmin(context.Context, *QueryOrgUsersRequest) (*BaseResponse, error)
	SetOrgAdmin(context.Context, *SetOrgAdminRequest) (*BaseResponse, error)
	QueryUsersOrg(context.Context, *QueryUsersOrgRequest) (*BaseResponse, error)
	mustEmbedUnimplementedInternalOrgServiceServer()
}

// UnimplementedInternalOrgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInternalOrgServiceServer struct {
}

func (UnimplementedInternalOrgServiceServer) QueryOrg(context.Context, *QueryOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) CreateOrg(context.Context, *CreateOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) UpdateOrg(context.Context, *UpdateOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) QueryUserOrg(context.Context, *QueryUserOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) SetUserOrg(context.Context, *SetUserOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) RemoveUserOrg(context.Context, *RemoveUserOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) QueryOrgUsers(context.Context, *QueryOrgUsersRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrgUsers not implemented")
}
func (UnimplementedInternalOrgServiceServer) QueryOrgAdmin(context.Context, *QueryOrgUsersRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrgAdmin not implemented")
}
func (UnimplementedInternalOrgServiceServer) SetOrgAdmin(context.Context, *SetOrgAdminRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetOrgAdmin not implemented")
}
func (UnimplementedInternalOrgServiceServer) QueryUsersOrg(context.Context, *QueryUsersOrgRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUsersOrg not implemented")
}
func (UnimplementedInternalOrgServiceServer) mustEmbedUnimplementedInternalOrgServiceServer() {}

// UnsafeInternalOrgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalOrgServiceServer will
// result in compilation errors.
type UnsafeInternalOrgServiceServer interface {
	mustEmbedUnimplementedInternalOrgServiceServer()
}

func RegisterInternalOrgServiceServer(s grpc.ServiceRegistrar, srv InternalOrgServiceServer) {
	s.RegisterService(&InternalOrgService_ServiceDesc, srv)
}

func _InternalOrgService_QueryOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).QueryOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_QueryOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).QueryOrg(ctx, req.(*QueryOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_CreateOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).CreateOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_CreateOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).CreateOrg(ctx, req.(*CreateOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_UpdateOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).UpdateOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_UpdateOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).UpdateOrg(ctx, req.(*UpdateOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_QueryUserOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).QueryUserOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_QueryUserOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).QueryUserOrg(ctx, req.(*QueryUserOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_SetUserOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).SetUserOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_SetUserOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).SetUserOrg(ctx, req.(*SetUserOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_RemoveUserOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).RemoveUserOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_RemoveUserOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).RemoveUserOrg(ctx, req.(*RemoveUserOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_QueryOrgUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrgUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).QueryOrgUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_QueryOrgUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).QueryOrgUsers(ctx, req.(*QueryOrgUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_QueryOrgAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrgUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).QueryOrgAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_QueryOrgAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).QueryOrgAdmin(ctx, req.(*QueryOrgUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_SetOrgAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOrgAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).SetOrgAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_SetOrgAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).SetOrgAdmin(ctx, req.(*SetOrgAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalOrgService_QueryUsersOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalOrgServiceServer).QueryUsersOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalOrgService_QueryUsersOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalOrgServiceServer).QueryUsersOrg(ctx, req.(*QueryUsersOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalOrgService_ServiceDesc is the grpc.ServiceDesc for InternalOrgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalOrgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InternalOrgService",
	HandlerType: (*InternalOrgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryOrg",
			Handler:    _InternalOrgService_QueryOrg_Handler,
		},
		{
			MethodName: "CreateOrg",
			Handler:    _InternalOrgService_CreateOrg_Handler,
		},
		{
			MethodName: "UpdateOrg",
			Handler:    _InternalOrgService_UpdateOrg_Handler,
		},
		{
			MethodName: "QueryUserOrg",
			Handler:    _InternalOrgService_QueryUserOrg_Handler,
		},
		{
			MethodName: "SetUserOrg",
			Handler:    _InternalOrgService_SetUserOrg_Handler,
		},
		{
			MethodName: "RemoveUserOrg",
			Handler:    _InternalOrgService_RemoveUserOrg_Handler,
		},
		{
			MethodName: "QueryOrgUsers",
			Handler:    _InternalOrgService_QueryOrgUsers_Handler,
		},
		{
			MethodName: "QueryOrgAdmin",
			Handler:    _InternalOrgService_QueryOrgAdmin_Handler,
		},
		{
			MethodName: "SetOrgAdmin",
			Handler:    _InternalOrgService_SetOrgAdmin_Handler,
		},
		{
			MethodName: "QueryUsersOrg",
			Handler:    _InternalOrgService_QueryUsersOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "InternalOrgService.proto",
}
