// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.2
// source: InternalOrgService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Org struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name         *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	TeamId       *int32  `protobuf:"varint,3,req,name=teamId" json:"teamId,omitempty"`
	Domain       *string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	AllowDomains *string `protobuf:"bytes,5,opt,name=allowDomains" json:"allowDomains,omitempty"`
	CreatedAt    *int64  `protobuf:"varint,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt    *int64  `protobuf:"varint,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	SsoOrgId     *string `protobuf:"bytes,8,opt,name=ssoOrgId" json:"ssoOrgId,omitempty"`
	Logo         *string `protobuf:"bytes,9,opt,name=logo" json:"logo,omitempty"`
	TeamName     *string `protobuf:"bytes,10,opt,name=teamName" json:"teamName,omitempty"`
}

func (x *Org) Reset() {
	*x = Org{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{0}
}

func (x *Org) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Org) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Org) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

func (x *Org) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *Org) GetAllowDomains() string {
	if x != nil && x.AllowDomains != nil {
		return *x.AllowDomains
	}
	return ""
}

func (x *Org) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *Org) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *Org) GetSsoOrgId() string {
	if x != nil && x.SsoOrgId != nil {
		return *x.SsoOrgId
	}
	return ""
}

func (x *Org) GetLogo() string {
	if x != nil && x.Logo != nil {
		return *x.Logo
	}
	return ""
}

func (x *Org) GetTeamName() string {
	if x != nil && x.TeamName != nil {
		return *x.TeamName
	}
	return ""
}

type QueryOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgIDs     []string `protobuf:"bytes,1,rep,name=orgIDs" json:"orgIDs,omitempty"`          // The list of org IDs to query
	TeamIds    []int32  `protobuf:"varint,2,rep,name=teamIds" json:"teamIds,omitempty"`       // The list of team IDs to query
	PageNumber *int32   `protobuf:"varint,3,opt,name=pageNumber" json:"pageNumber,omitempty"` // orgIDs\teamIds will be ignored if page_number is set
	PageSize   *int32   `protobuf:"varint,4,opt,name=pageSize" json:"pageSize,omitempty"`
	SsoOrgIds  []string `protobuf:"bytes,5,rep,name=ssoOrgIds" json:"ssoOrgIds,omitempty"`
}

func (x *QueryOrgRequest) Reset() {
	*x = QueryOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrgRequest) ProtoMessage() {}

func (x *QueryOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrgRequest.ProtoReflect.Descriptor instead.
func (*QueryOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{1}
}

func (x *QueryOrgRequest) GetOrgIDs() []string {
	if x != nil {
		return x.OrgIDs
	}
	return nil
}

func (x *QueryOrgRequest) GetTeamIds() []int32 {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

func (x *QueryOrgRequest) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

func (x *QueryOrgRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *QueryOrgRequest) GetSsoOrgIds() []string {
	if x != nil {
		return x.SsoOrgIds
	}
	return nil
}

type QueryOrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orgs       []*Org `protobuf:"bytes,1,rep,name=orgs" json:"orgs,omitempty"`
	TotalCount *int32 `protobuf:"varint,2,req,name=totalCount" json:"totalCount,omitempty"`
}

func (x *QueryOrgResponse) Reset() {
	*x = QueryOrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrgResponse) ProtoMessage() {}

func (x *QueryOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrgResponse.ProtoReflect.Descriptor instead.
func (*QueryOrgResponse) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{2}
}

func (x *QueryOrgResponse) GetOrgs() []*Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

func (x *QueryOrgResponse) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

type CreateOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	TeamId       *int32  `protobuf:"varint,2,req,name=teamId" json:"teamId,omitempty"`
	Domain       *string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	AllowDomains *string `protobuf:"bytes,4,opt,name=allowDomains" json:"allowDomains,omitempty"`
	SsoOrgId     *string `protobuf:"bytes,5,opt,name=ssoOrgId" json:"ssoOrgId,omitempty"`
	Logo         *string `protobuf:"bytes,6,opt,name=logo" json:"logo,omitempty"`
}

func (x *CreateOrgRequest) Reset() {
	*x = CreateOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgRequest) ProtoMessage() {}

func (x *CreateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrgRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateOrgRequest) GetTeamId() int32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

func (x *CreateOrgRequest) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *CreateOrgRequest) GetAllowDomains() string {
	if x != nil && x.AllowDomains != nil {
		return *x.AllowDomains
	}
	return ""
}

func (x *CreateOrgRequest) GetSsoOrgId() string {
	if x != nil && x.SsoOrgId != nil {
		return *x.SsoOrgId
	}
	return ""
}

func (x *CreateOrgRequest) GetLogo() string {
	if x != nil && x.Logo != nil {
		return *x.Logo
	}
	return ""
}

// 修改Org
type UpdateOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name         *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain       *string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	AllowDomains *string `protobuf:"bytes,4,opt,name=allowDomains" json:"allowDomains,omitempty"`
	SsoOrgId     *string `protobuf:"bytes,5,opt,name=ssoOrgId" json:"ssoOrgId,omitempty"`
	Logo         *string `protobuf:"bytes,6,opt,name=logo" json:"logo,omitempty"`
}

func (x *UpdateOrgRequest) Reset() {
	*x = UpdateOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgRequest) ProtoMessage() {}

func (x *UpdateOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrgRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpdateOrgRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateOrgRequest) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *UpdateOrgRequest) GetAllowDomains() string {
	if x != nil && x.AllowDomains != nil {
		return *x.AllowDomains
	}
	return ""
}

func (x *UpdateOrgRequest) GetSsoOrgId() string {
	if x != nil && x.SsoOrgId != nil {
		return *x.SsoOrgId
	}
	return ""
}

func (x *UpdateOrgRequest) GetLogo() string {
	if x != nil && x.Logo != nil {
		return *x.Logo
	}
	return ""
}

type QueryUserOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
}

func (x *QueryUserOrgRequest) Reset() {
	*x = QueryUserOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserOrgRequest) ProtoMessage() {}

func (x *QueryUserOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserOrgRequest.ProtoReflect.Descriptor instead.
func (*QueryUserOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUserOrgRequest) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

type QueryUserOrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Org *Org `protobuf:"bytes,1,req,name=org" json:"org,omitempty"`
}

func (x *QueryUserOrgResponse) Reset() {
	*x = QueryUserOrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserOrgResponse) ProtoMessage() {}

func (x *QueryUserOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserOrgResponse.ProtoReflect.Descriptor instead.
func (*QueryUserOrgResponse) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{6}
}

func (x *QueryUserOrgResponse) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type QueryUsersOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid []string `protobuf:"bytes,1,rep,name=uid" json:"uid,omitempty"`
}

func (x *QueryUsersOrgRequest) Reset() {
	*x = QueryUsersOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUsersOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersOrgRequest) ProtoMessage() {}

func (x *QueryUsersOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersOrgRequest.ProtoReflect.Descriptor instead.
func (*QueryUsersOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{7}
}

func (x *QueryUsersOrgRequest) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

type QueryUsersOrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserOrg []*QueryUsersOrgResponse_UserOrg `protobuf:"bytes,1,rep,name=userOrg" json:"userOrg,omitempty"`
}

func (x *QueryUsersOrgResponse) Reset() {
	*x = QueryUsersOrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUsersOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersOrgResponse) ProtoMessage() {}

func (x *QueryUsersOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersOrgResponse.ProtoReflect.Descriptor instead.
func (*QueryUsersOrgResponse) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{8}
}

func (x *QueryUsersOrgResponse) GetUserOrg() []*QueryUsersOrgResponse_UserOrg {
	if x != nil {
		return x.UserOrg
	}
	return nil
}

type SetUserOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   []string `protobuf:"bytes,1,rep,name=uid" json:"uid,omitempty"`
	OrgID *string  `protobuf:"bytes,2,req,name=orgID" json:"orgID,omitempty"`
}

func (x *SetUserOrgRequest) Reset() {
	*x = SetUserOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserOrgRequest) ProtoMessage() {}

func (x *SetUserOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserOrgRequest.ProtoReflect.Descriptor instead.
func (*SetUserOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{9}
}

func (x *SetUserOrgRequest) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *SetUserOrgRequest) GetOrgID() string {
	if x != nil && x.OrgID != nil {
		return *x.OrgID
	}
	return ""
}

type SetUserOrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*SetUserOrgResponse_SetUserOrgResult `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (x *SetUserOrgResponse) Reset() {
	*x = SetUserOrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserOrgResponse) ProtoMessage() {}

func (x *SetUserOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserOrgResponse.ProtoReflect.Descriptor instead.
func (*SetUserOrgResponse) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{10}
}

func (x *SetUserOrgResponse) GetResult() []*SetUserOrgResponse_SetUserOrgResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type RemoveUserOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid []string `protobuf:"bytes,1,rep,name=uid" json:"uid,omitempty"`
}

func (x *RemoveUserOrgRequest) Reset() {
	*x = RemoveUserOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserOrgRequest) ProtoMessage() {}

func (x *RemoveUserOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserOrgRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserOrgRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveUserOrgRequest) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

type QueryOrgUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId    *string `protobuf:"bytes,1,opt,name=orgId" json:"orgId,omitempty"`
	SsoOrgId *string `protobuf:"bytes,2,opt,name=ssoOrgId" json:"ssoOrgId,omitempty"`
}

func (x *QueryOrgUsersRequest) Reset() {
	*x = QueryOrgUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrgUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrgUsersRequest) ProtoMessage() {}

func (x *QueryOrgUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrgUsersRequest.ProtoReflect.Descriptor instead.
func (*QueryOrgUsersRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{12}
}

func (x *QueryOrgUsersRequest) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *QueryOrgUsersRequest) GetSsoOrgId() string {
	if x != nil && x.SsoOrgId != nil {
		return *x.SsoOrgId
	}
	return ""
}

type OrgAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Role    *int32  `protobuf:"varint,2,opt,name=role" json:"role,omitempty"`
	Operate *int32  `protobuf:"varint,3,opt,name=operate" json:"operate,omitempty"`
}

func (x *OrgAdmin) Reset() {
	*x = OrgAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgAdmin) ProtoMessage() {}

func (x *OrgAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgAdmin.ProtoReflect.Descriptor instead.
func (*OrgAdmin) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{13}
}

func (x *OrgAdmin) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *OrgAdmin) GetRole() int32 {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return 0
}

func (x *OrgAdmin) GetOperate() int32 {
	if x != nil && x.Operate != nil {
		return *x.Operate
	}
	return 0
}

type QueryOrgAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgAdmin []*OrgAdmin `protobuf:"bytes,1,rep,name=orgAdmin" json:"orgAdmin,omitempty"`
}

func (x *QueryOrgAdminResponse) Reset() {
	*x = QueryOrgAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrgAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrgAdminResponse) ProtoMessage() {}

func (x *QueryOrgAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrgAdminResponse.ProtoReflect.Descriptor instead.
func (*QueryOrgAdminResponse) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{14}
}

func (x *QueryOrgAdminResponse) GetOrgAdmin() []*OrgAdmin {
	if x != nil {
		return x.OrgAdmin
	}
	return nil
}

type SetOrgAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *string     `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	OrgAdmin []*OrgAdmin `protobuf:"bytes,2,rep,name=orgAdmin" json:"orgAdmin,omitempty"`
}

func (x *SetOrgAdminRequest) Reset() {
	*x = SetOrgAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOrgAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrgAdminRequest) ProtoMessage() {}

func (x *SetOrgAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrgAdminRequest.ProtoReflect.Descriptor instead.
func (*SetOrgAdminRequest) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{15}
}

func (x *SetOrgAdminRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SetOrgAdminRequest) GetOrgAdmin() []*OrgAdmin {
	if x != nil {
		return x.OrgAdmin
	}
	return nil
}

type QueryUsersOrgResponse_UserOrg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Org *Org    `protobuf:"bytes,2,req,name=org" json:"org,omitempty"`
}

func (x *QueryUsersOrgResponse_UserOrg) Reset() {
	*x = QueryUsersOrgResponse_UserOrg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUsersOrgResponse_UserOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersOrgResponse_UserOrg) ProtoMessage() {}

func (x *QueryUsersOrgResponse_UserOrg) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersOrgResponse_UserOrg.ProtoReflect.Descriptor instead.
func (*QueryUsersOrgResponse_UserOrg) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{8, 0}
}

func (x *QueryUsersOrgResponse_UserOrg) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *QueryUsersOrgResponse_UserOrg) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

type SetUserOrgResponse_SetUserOrgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Success *bool   `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	Error   *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (x *SetUserOrgResponse_SetUserOrgResult) Reset() {
	*x = SetUserOrgResponse_SetUserOrgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InternalOrgService_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserOrgResponse_SetUserOrgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserOrgResponse_SetUserOrgResult) ProtoMessage() {}

func (x *SetUserOrgResponse_SetUserOrgResult) ProtoReflect() protoreflect.Message {
	mi := &file_InternalOrgService_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserOrgResponse_SetUserOrgResult.ProtoReflect.Descriptor instead.
func (*SetUserOrgResponse_SetUserOrgResult) Descriptor() ([]byte, []int) {
	return file_InternalOrgService_proto_rawDescGZIP(), []int{10, 0}
}

func (x *SetUserOrgResponse_SetUserOrgResult) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *SetUserOrgResponse_SetUserOrgResult) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *SetUserOrgResponse_SetUserOrgResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_InternalOrgService_proto protoreflect.FileDescriptor

var file_InternalOrgService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x02, 0x0a, 0x03, 0x4f, 0x72, 0x67,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x9d, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x74,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x73,
	0x22, 0x4c, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x04, 0x6f, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x04, 0x6f, 0x72, 0x67, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xaa,
	0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f,
	0x22, 0x27, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x4f, 0x72, 0x67, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x28, 0x0a, 0x14, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4f, 0x72, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x1a, 0x33, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x04, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x22, 0x3b, 0x0a, 0x11,
	0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x22, 0xa8, 0x01, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x54,
	0x0a, 0x10, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x28, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x48,
	0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x73, 0x6f, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x08, 0x4f, 0x72, 0x67, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x08, 0x6f, 0x72, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x4f, 0x72, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x22, 0x4b, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x6f, 0x72,
	0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4f,
	0x72, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x32, 0x94, 0x04, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x72,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x72, 0x67, 0x12, 0x10, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x67, 0x12, 0x11, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x67, 0x12, 0x11, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x72, 0x67, 0x12, 0x14, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x12, 0x12, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x12, 0x15, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x15, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4f, 0x72, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4f, 0x72, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x13, 0x2e,
	0x53, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4f,
	0x72, 0x67, 0x12, 0x15, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4f,
	0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x0a, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x77, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x67, 0x63, 0x6d, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x6f, 0x72, 0x67, 0x73, 0x50, 0x01, 0x5a, 0x06, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_InternalOrgService_proto_rawDescOnce sync.Once
	file_InternalOrgService_proto_rawDescData = file_InternalOrgService_proto_rawDesc
)

func file_InternalOrgService_proto_rawDescGZIP() []byte {
	file_InternalOrgService_proto_rawDescOnce.Do(func() {
		file_InternalOrgService_proto_rawDescData = protoimpl.X.CompressGZIP(file_InternalOrgService_proto_rawDescData)
	})
	return file_InternalOrgService_proto_rawDescData
}

var file_InternalOrgService_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_InternalOrgService_proto_goTypes = []interface{}{
	(*Org)(nil),                                 // 0: Org
	(*QueryOrgRequest)(nil),                     // 1: QueryOrgRequest
	(*QueryOrgResponse)(nil),                    // 2: QueryOrgResponse
	(*CreateOrgRequest)(nil),                    // 3: CreateOrgRequest
	(*UpdateOrgRequest)(nil),                    // 4: UpdateOrgRequest
	(*QueryUserOrgRequest)(nil),                 // 5: QueryUserOrgRequest
	(*QueryUserOrgResponse)(nil),                // 6: QueryUserOrgResponse
	(*QueryUsersOrgRequest)(nil),                // 7: QueryUsersOrgRequest
	(*QueryUsersOrgResponse)(nil),               // 8: QueryUsersOrgResponse
	(*SetUserOrgRequest)(nil),                   // 9: SetUserOrgRequest
	(*SetUserOrgResponse)(nil),                  // 10: SetUserOrgResponse
	(*RemoveUserOrgRequest)(nil),                // 11: RemoveUserOrgRequest
	(*QueryOrgUsersRequest)(nil),                // 12: QueryOrgUsersRequest
	(*OrgAdmin)(nil),                            // 13: OrgAdmin
	(*QueryOrgAdminResponse)(nil),               // 14: QueryOrgAdminResponse
	(*SetOrgAdminRequest)(nil),                  // 15: SetOrgAdminRequest
	(*QueryUsersOrgResponse_UserOrg)(nil),       // 16: QueryUsersOrgResponse.UserOrg
	(*SetUserOrgResponse_SetUserOrgResult)(nil), // 17: SetUserOrgResponse.SetUserOrgResult
	(*BaseResponse)(nil),                        // 18: BaseResponse
}
var file_InternalOrgService_proto_depIdxs = []int32{
	0,  // 0: QueryOrgResponse.orgs:type_name -> Org
	0,  // 1: QueryUserOrgResponse.org:type_name -> Org
	16, // 2: QueryUsersOrgResponse.userOrg:type_name -> QueryUsersOrgResponse.UserOrg
	17, // 3: SetUserOrgResponse.result:type_name -> SetUserOrgResponse.SetUserOrgResult
	13, // 4: QueryOrgAdminResponse.orgAdmin:type_name -> OrgAdmin
	13, // 5: SetOrgAdminRequest.orgAdmin:type_name -> OrgAdmin
	0,  // 6: QueryUsersOrgResponse.UserOrg.org:type_name -> Org
	1,  // 7: InternalOrgService.QueryOrg:input_type -> QueryOrgRequest
	3,  // 8: InternalOrgService.CreateOrg:input_type -> CreateOrgRequest
	4,  // 9: InternalOrgService.UpdateOrg:input_type -> UpdateOrgRequest
	5,  // 10: InternalOrgService.QueryUserOrg:input_type -> QueryUserOrgRequest
	9,  // 11: InternalOrgService.SetUserOrg:input_type -> SetUserOrgRequest
	11, // 12: InternalOrgService.RemoveUserOrg:input_type -> RemoveUserOrgRequest
	12, // 13: InternalOrgService.QueryOrgUsers:input_type -> QueryOrgUsersRequest
	12, // 14: InternalOrgService.QueryOrgAdmin:input_type -> QueryOrgUsersRequest
	15, // 15: InternalOrgService.SetOrgAdmin:input_type -> SetOrgAdminRequest
	7,  // 16: InternalOrgService.QueryUsersOrg:input_type -> QueryUsersOrgRequest
	18, // 17: InternalOrgService.QueryOrg:output_type -> BaseResponse
	18, // 18: InternalOrgService.CreateOrg:output_type -> BaseResponse
	18, // 19: InternalOrgService.UpdateOrg:output_type -> BaseResponse
	18, // 20: InternalOrgService.QueryUserOrg:output_type -> BaseResponse
	18, // 21: InternalOrgService.SetUserOrg:output_type -> BaseResponse
	18, // 22: InternalOrgService.RemoveUserOrg:output_type -> BaseResponse
	18, // 23: InternalOrgService.QueryOrgUsers:output_type -> BaseResponse
	18, // 24: InternalOrgService.QueryOrgAdmin:output_type -> BaseResponse
	18, // 25: InternalOrgService.SetOrgAdmin:output_type -> BaseResponse
	18, // 26: InternalOrgService.QueryUsersOrg:output_type -> BaseResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_InternalOrgService_proto_init() }
func file_InternalOrgService_proto_init() {
	if File_InternalOrgService_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_InternalOrgService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Org); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserOrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUsersOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUsersOrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserOrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrgUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrgAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOrgAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUsersOrgResponse_UserOrg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_InternalOrgService_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserOrgResponse_SetUserOrgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InternalOrgService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_InternalOrgService_proto_goTypes,
		DependencyIndexes: file_InternalOrgService_proto_depIdxs,
		MessageInfos:      file_InternalOrgService_proto_msgTypes,
	}.Build()
	File_InternalOrgService_proto = out.File
	file_InternalOrgService_proto_rawDesc = nil
	file_InternalOrgService_proto_goTypes = nil
	file_InternalOrgService_proto_depIdxs = nil
}
