name: "Go"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go env
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Verify Go dependencies
        run: go mod verify
      - name: Run unit tests
        run: go test -v ./...
      - name: Goreleaser check
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: check
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go env
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"
          cache: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: -v --timeout=5m
          only-new-issues: false
          install-mode: "binary"
